linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - exportloopref # Deprecated
    - forbidigo
    - gci
    - gochecknoglobals
    - gosec
    - nestif
    - prealloc
    - tagliatelle
    - varnamelen
    - wsl
  fast: false

run:
  go: "1.23"
  timeout: 10m
