linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - exportloopref # Deprecated
    - forbidigo
    - gci
    - gochecknoglobals
    - gosec
    - nestif
    - prealloc
    - tagliatelle
    - varnamelen
    - wsl
    - stylecheck
    - nlreturn
    - revive
    - gofumpt
  fast: false

run:
  go: "1.23"
  timeout: 10m
