run:
  timeout: 10m

linters:
  enable-all: true
  disable:
    - depguard # False positive
    - exhaustruct
    - exportloopref # Deprecated
    - forbidigo # Too strict
    - gci
    - gochecknoglobals
    - gofumpt # False positive
    - nestif
    - nlreturn
    - noctx # Too strict
    - paralleltest # Not relevant
    - prealloc # Too strict
    - revive
    - stylecheck # Too strict
    - tagliatelle
    - varnamelen
    - wrapcheck # Too strict
    - wsl
  fast: false

linters-settings:
  gocritic:
    enable-all: true
    disabled-checks:
      - captLocal
      - commentedOutCode
  govet:
    enable-all: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  show-stats: true
  sort-results: true
