linters:
  enable-all: true
  disable:
    - depguard # False positive
    - exhaustruct
    - exportloopref # Deprecated
    - forbidigo # Too strict
    - gci
    - gochecknoglobals
    - gofumpt # False positive
    - gosec
    - nestif
    - nlreturn
    - noctx # Too strict
    - paralleltest # Not relevant
    - prealloc # Too strict
    - revive
    - stylecheck # Too strict
    - tagliatelle
    - varnamelen
    - wsl
  fast: false

linters-settings:
  gocritic:
    enable-all: true
    disabled-checks:
      - captLocal
      - commentedOutCode
  govet:
    enable-all: true

run:
  go: "1.23"
  timeout: 10m
