---
- name: Deploy malstat-scrapper
  hosts: all
  become: true
  gather_facts: true
  vars:
    install_loc: /usr/local/bin/malstat-scrapper
    output_csv: malstat.csv
  tasks:
    - name: Copy the executable to the remote machine
      ansible.builtin.copy:
        src: ../../scrapper
        dest: "{{ install_loc }}"
        backup: true
        mode: preserve

    - name: Setup the cronjob
      ansible.builtin.cron:
        name: malstat-scrapper
        hour: 4
        minute: 20
        job: "malstat-scrapper scrap --top 500 --csv $HOME/{{ output_csv }} > /dev/null"
        state: present
