name: Publish Releases to GitHub Container Registry

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push main branch
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: >-
            ghcr.io/kokuban/scrapper:${{ github.ref_name }},
            ghcr.io/kokuban/scrapper:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
